application: hardwave-pedomemo
version: 3
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /js
  static_dir: js

- url: /.*
  script: pedomemo.py

