application: hardwave-pedomemo
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /.*
  script: pedomemo.py

