application: pedo-memo
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest


handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /admin/.*
  script: admin.app
  login: admin

- url: /html
  static_dir: html

- url: /js
  static_dir: js

- url: /.*
  script: pedomemo.app

